### ISSUE TITLE
Won't Run Under Rasbian OS

### ISSUE THREAD

**Issue by Vanguard4893** [misdoro/Electronic_load_px100#12]
I'm having trouble getting this to run under Rasbian, Python v3.7.3. I'm no programmer by any means, any ideas on a fix?

`Traceback (most recent call last):
  File "./main.py", line 56, in <module>
    Main()
  File "./main.py", line 21, in __init__
    GUI(self)
  File "/home/pi/Load/gui/gui.py", line 209, in __init__
    self.window = MainWindow()
  File "/home/pi/Load/gui/gui.py", line 42, in __init__
    uic.loadUi('gui/main.ui', self)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 226, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 1021, in parse
    actor(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 828, in createUserInterface
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 273, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 503, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 546, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 806, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 264, in createWidget
    self.stack.push(self.setupObject(widget_class, parent, elem))
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 230, in setupObject
    self.wprops.setProperties(obj, branch)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/properties.py", line 415, in setProperties
    prop_value = self.convert(prop, widget)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/properties.py", line 378, in convert
    return func(prop[0], **args)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/properties.py", line 129, in _enum
    return self._pyEnumMember(prop.text)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/properties.py", line 117, in _pyEnumMember
    return getattr(scope, membername)
AttributeError: type object 'QAbstractSpinBox' has no attribute 'AdaptiveDecimalStepType'`

**Comment by misdoro** [comment]
Hi!
What is the pyqt5 version you are running?
`pip show pyqt5` to check.

I believe at least version 5.12 is required to run, I'm using 5.15.4 and it works fine.

**Comment by Vanguard4893** [comment]
This does look like the root cause, however the later versions required to run this aren't in the Pi repositories, and getting it to compile didn't end well for me. I'll close this, and wait for the next version of Raspbian OS, which should have a later version by default.

Cheers
