### ISSUE TITLE
Crash on open because of pandas 2.0, append (previously deprecated) was removed.

### ISSUE THREAD

**Issue by upya4ko** [misdoro/Electronic_load_px100#22]
I try run logger but get error:
```
python main.py
Detecting instruments...
ASRL/dev/ttyUSB0::INSTR
SerialInstrument at ASRL/dev/ttyUSB0::INSTR
probe
found PX100
readAll
readAll
readAll
readAll
common /home/admin home /home/admin sel /home/admin
swcccv_reset
{'is_on': 0.0, 'voltage': 3.966, 'current': 0.0, 'time': datetime.time(0, 6, 39), 'cap_ah': 0.11, 'cap_wh': 0.0, 'temp': 29.0, 'set_current': 1.0, 'set_voltage': 3.0, 'set_timer': datetime.time(0, 0)}
Traceback (most recent call last):
  File "/mnt/usb/DL24_BLE_Logger-main/Electronic_load_px100/main.py", line 34, in data_callback
    self.datastore.append(data)
  File "/mnt/usb/DL24_BLE_Logger-main/Electronic_load_px100/data_store.py", line 21, in append
    self.data = self.data.append(row, ignore_index=True)
                ^^^^^^^^^^^^^^^^
  File "/home/admin/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 6202, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
{'is_on': 0.0, 'voltage': 3.966, 'current': 0.0, 'time': datetime.time(0, 6, 39), 'cap_ah': 0.11, 'cap_wh': 0.0, 'temp': 29.0, 'set_current': 1.0, 'set_voltage': 3.0, 'set_timer': datetime.time(0, 0)}
Traceback (most recent call last):
  File "/mnt/usb/DL24_Logger-main/Electronic_load_px100/main.py", line 34, in data_callback
    self.datastore.append(data)
  File "/mnt/usb/DL24_Logger-main/Electronic_load_px100/data_store.py", line 21, in append
    self.data = self.data.append(row, ignore_index=True)
                ^^^^^^^^^^^^^^^^
  File "/home/admin/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 6202, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
Aborted (core dumped)
```
https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append

I try replace ```self.datastore.append(data)``` to ``` self.datastore._append(data) ```
get error
```
$ python main.py
Detecting instruments...
common /home/upya4ko home /home/upya4ko sel /home/upya4ko
swcccv_reset
ASRL/dev/ttyUSB0::INSTR
SerialInstrument at ASRL/dev/ttyUSB0::INSTR
probe
<class 'pyvisa.errors.VisaIOError'>
('VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.',)
VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
error reading bytes
no answer
ko
No instruments found
```

**Comment by misdoro** [comment]
Hi, a fix can be to pin the pandas version to below 2.0 in requirements.txt

**Comment by upya4ko** [comment]
> Hi, a fix can be to pin the pandas version to below 2.0 in requirements.txt

Confirm, thank you, this help:
```
diff --git a/requirements.txt b/requirements.txt
index e23b079..d360ea5 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,6 +1,6 @@
 matplotlib
 numpy
-pandas
+pandas==1.5.3
 pyqt5
 pyvisa
 pyvisa-py
```
