### ISSUE TITLE
This will work with DL24 over bluetooth

### ISSUE THREAD

**Issue by Darthmonkey** [misdoro/Electronic_load_px100#26]
Although clearly designed for PX100, this works with an ATorch DL24 when paired over Bluetooth.
Perhaps the description or title can include that?

**Comment by ways** [comment]
> Although clearly designed for PX100, this works with an ATorch DL24 when paired over Bluetooth. Perhaps the description or title can include that?

How? I'm able to connect via bluetooth, but the app says 

> swcccv_reset
> No instruments found

Ubuntu 22.04

![image](https://github.com/user-attachments/assets/81fca1db-4b0d-4a40-99a6-d5452545e660)

Note that I had to switch pandas to latest version, just to get the app to start, thus my versions are

> Package           Version
> ----------------- -----------
> async-timeout     4.0.3
> contourpy         1.2.1
> cycler            0.12.1
> fonttools         4.53.1
> ifaddr            0.2.0
> kiwisolver        1.4.5
> matplotlib        3.9.2
> numpy             2.0.1
> packaging         24.1
> pandas            2.2.2
> pillow            10.4.0
> pip               22.0.2
> pyparsing         3.1.2
> PyQt5             5.15.11
> PyQt5-Qt5         5.15.14
> PyQt5_sip         12.15.0
> pyserial          3.5
> python-dateutil   2.9.0.post0
> pytz              2024.1
> PyVISA            1.14.1
> PyVISA-py         0.7.2
> setuptools        59.6.0
> six               1.16.0
> typing_extensions 4.12.2
> tzdata            2024.1
> zeroconf          0.132.2

If I don't do that the app doesn't start, and shows:

```
~/src/Electronic_load_px100$ python main.py
Traceback (most recent call last):
  File "/home/lars/Downloads/src/Electronic_load_px100/main.py", line 6, in <module>
    from data_store import DataStore
  File "/home/lars/Downloads/src/Electronic_load_px100/data_store.py", line 4, in <module>
    from pandas import DataFrame
  File "/home/lars/Downloads/src/Electronic_load_px100/venv/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/lars/Downloads/src/Electronic_load_px100/venv/lib/python3.10/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/home/lars/Downloads/src/Electronic_load_px100/venv/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/lars/Downloads/src/Electronic_load_px100/venv/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/lars/Downloads/src/Electronic_load_px100/venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/lars/Downloads/src/Electronic_load_px100/venv/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

That was a lot info in one post...

**Comment by misdoro** [comment]
:thinking: @ways from my experience DL24 can be slow to switch to PX100 protocol, sometimes it silently swallows a few first commands, needing a few seconds or few attempts to start working again.

Can you try re-starting this program second time without changing anything else?

**Comment by ways** [comment]
After a reboot I'm able to get this:

```
(venv) lars@tenk:~/src/Electronic_load_px100$ python3 main.py
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Detecting instruments...
common /home/lars home /home/lars sel /home/lars/Downloads
swcccv_reset
ASRL/dev/ttyS0::INSTR
err opening instrument
ASRL/dev/ttyS1::INSTR
err opening instrument
ASRL/dev/ttyS2::INSTR
err opening instrument
ASRL/dev/ttyS3::INSTR
err opening instrument
ASRL/dev/ttyS4::INSTR
err opening instrument
ASRL/dev/ttyS5::INSTR
err opening instrument
ASRL/dev/ttyS6::INSTR
err opening instrument
ASRL/dev/ttyS7::INSTR
err opening instrument
ASRL/dev/ttyS8::INSTR
err opening instrument
ASRL/dev/ttyS9::INSTR
err opening instrument
ASRL/dev/ttyS10::INSTR
err opening instrument
ASRL/dev/ttyS11::INSTR
err opening instrument
ASRL/dev/ttyS12::INSTR
err opening instrument
ASRL/dev/ttyS13::INSTR
err opening instrument
ASRL/dev/ttyS14::INSTR
err opening instrument
ASRL/dev/ttyS15::INSTR
err opening instrument
ASRL/dev/ttyS16::INSTR
err opening instrument
ASRL/dev/ttyS17::INSTR
err opening instrument
ASRL/dev/ttyS18::INSTR
err opening instrument
ASRL/dev/ttyS19::INSTR
err opening instrument
ASRL/dev/ttyS20::INSTR
err opening instrument
ASRL/dev/ttyS21::INSTR
err opening instrument
ASRL/dev/ttyS22::INSTR
err opening instrument
ASRL/dev/ttyS23::INSTR
err opening instrument
ASRL/dev/ttyS24::INSTR
err opening instrument
ASRL/dev/ttyS25::INSTR
err opening instrument
ASRL/dev/ttyS26::INSTR
err opening instrument
ASRL/dev/ttyS27::INSTR
err opening instrument
ASRL/dev/ttyS28::INSTR
err opening instrument
ASRL/dev/ttyS29::INSTR
err opening instrument
ASRL/dev/ttyS30::INSTR
err opening instrument
ASRL/dev/ttyS31::INSTR
err opening instrument
No instruments found
no data
```

Still no successfull connection. Have checked permissions on /dev/ttyS*.

**Comment by Darthmonkey** [comment]
I haven't tried this in Ubuntu, but I did find there are two Bluetooth devices when attempting to connect it in Windows. 
They don't both show immediately, so perhaps try variations on:
1. Remove any existing 'DL24' Bluetooth connected devices.
2. Reboot the DL24, then attempt to connect to it via Bluetooth, and choose the 'DL24_SPP' (assuming you have the option) after waiting a few seconds for it to show up.
3. Open Battery tester PX100, and wait for it to connect. Going over this to check my methods, I found it didn't work the first time, so I retried using the same methods, and it worked. BT can be a bit flaky.
![image](https://github.com/user-attachments/assets/7d9fdcb4-3be6-4202-a7e2-d7415dc99e02)

**Comment by Rootthecause** [comment]
I was using the DL24 with misdoro's px100 code for a while now, but since I updated python/pandas I'm having trouble with internal resistance mesasurement (random missing values and not returning from 0 to the set current) and enableing the load via the "Enabled" button on the GUI. I need to start the test by physically pressing the start button on the load instead. Sometimes the program crashed randomly mid-test.

So I'm currently using the Fork by Jay2k1 [https://github.com/Jay2k1/Electronic_load_DL24](https://github.com/Jay2k1/Electronic_load_DL24)
Surprisingly it all seems to work even with my updated python/pandas with the added benefit of Power and (internal)Temp logging. Bluethoot connection seems to work better as well: While misdoro's code automatically connected to the load in 2 out of 10 tries on programm start-up, the code by Jay2k1 worked 5 out of 10 times. Could be a fluke, but still. 

So I wonder, if the issue is on my side with misdoro's code because I'm using different hardware?

**Comment by Darthmonkey** [comment]
For anyone who isn't a developer (probably no one here) Roodthecause's suggestion does work (thanks!). The installation and running instructions on Github are typically woefully inadequate (not a criticism of the developer, simply a statement of all devs). I shall attempt to correct them here - Note this is one of several paths you can take:
1. Install Python - this very much depends on how you want to install it, simply Google 'install pyton for 'windows','mac',etc.
2. Open a PowerShell window, and ensure Python is installed correctly `py.exe --version` should show v3 or higher.
3. Click the [link to the Electronic_load_DL24](https://github.com/Jay2k1/Electronic_load_DL24) github page, and clone it to a folder on your system by using the code below (I'm using C:\scripts as a base folder): 
`git clone https://github.com/Jay2k1/Electronic_load_DL24.git 'c:\scripts\DL24LoadTester' --progress`
4. Double click the 'main.py' script in the 'DL24LoadTester' folder. Don't try to run it from the command line, it won't show the GUI.
5. Create a shortcut to main.py in the same folder, and call it something like 'DL24 Battery Tester', then add it to the start menu, optionally changing the icon first.

To offer a potential answer Rootthecause's question, I suspect it wasn't due to a python update, although I have no basis for that, other than to suggest that it may be more likely a temporary Bluetooth dropout causing crashing and random missing values. I purchased a new-ish V5 BT dongle, and put it on a USB extension cable, running it to the top of a window. This allows me coverage through most of the house, as opposed to some strong and some extremely patchy signal areas.

**Comment by Rootthecause** [comment]
@Darthmonkey 
Yes, it seems to be a BT dropout. I was able to screenshot the event:
![error](https://github.com/user-attachments/assets/928204c7-48af-4cbf-9409-8485de637799)
But this is still weird, because the load is just ~1 m away from the MacBook. Normally I can get stable BT connections across the house through 3 Walls.

Note to your instructions: 
I'm running on macOS (Ventura 13.6). For me it's is pretty much how the dev wrote it in the readme.

0. connect to the load via BT, find the one saying "DL24_SPP". After the connection is made, it might disconnect on its own after a few seconds (seems to be normal). You can try connect to it again, but it might connect on its own later.
1. download the files (unpack zip)
2. open terminal
3. type `cd ` and drag the folder in the terminal window to get the path -> hit enter
4. type `python main.py`   Note: Depending on your Python istallation, sometimes `python3` is required instead of `python`
-> hit enter. The GUI will open. 

With some luck, the Programm will automatically connect to the load on program startup. If not, connect to the load again in the BT menu and restart the program (close and type `python main.py` again or press arrow up for the last command)
Btw. I'm running python 3.10.13

**Comment by Abdull** [comment]
I did the following steps for version https://github.com/misdoro/Electronic_load_px100/tree/be917afdaf9b361c7a3b5b8457e706a63e4c65c8 to work on my system (Debian 12, KDE Wayland, Framework 13 AMD laptop):

```
# clone project
git clone https://github.com/misdoro/Electronic_load_px100

cd Electronic_load_px100/

# create venv virtual environment
python -m venv .

# activate venv virtual environment
source bin/activate

# set numpy dependency to last (latest?) 1.x version.
# this fixes the numpy 2.x error message ...
#   ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
# ... reported in _this_ issue
#
# see https://stackoverflow.com/a/78641304/923560
# see https://github.com/numpy/numpy/releases/tag/v1.26.4
nano requirements.txt
# change "numpy" to "numpy==1.26.4"

# install requirements
pip install -r requirements.txt

# install pip-psutil. I'm not sure if this is required, but it was suggested to me at "python main.py" start-up by the following warning message:
#   Electronic_load_px100/lib/python3.11/site-packages/pyvisa_py/tcpip.py:409: UserWarning: TCPIP:instr resource discovery is limited to the default interface.Install psutil:
#   pip install psutil if you want to scan all interfaces.
pip install psutil

# provide the DL24 with its own power so its screen turns on. 
# find out the MAC address of bluetooth device "DL24_SPP", e.g. by using a GUI such as toolBLEx.
# The "DL24_SPP" MAC address is different from the "DL24_BLE" MAC address at the highest byte, e.g.
#   DL24_SPP: 4D:E1:C5:E7:9A:AA
#   DL24_BLE: 4C:E1:C5:E7:9A:AA

# in another shell, sudo-rfcomm-connect to the previously identified DL24_SPP MAC address: ...
sudo rfcomm connect hci0 4D:E1:C5:E7:9A:AA

# ... the shell should provide output similar to this:
#   Connected /dev/rfcomm0 to 4D:E1:C5:E7:9A:AA on channel 1
#   Press CTRL-C for hangup
# keep this shell like it this

# in the other shell with the activated venv virtual environment, execute main.py:
python main.py

# if everything works fine, you should see output similar to the following:
#   qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
#   common /home/abdull home /home/abdull sel /home/abdull
#   swcccv_reset
#   Detecting instruments...
#   ASRL/dev/ttyS0::INSTR
#   err opening instrument
#   ASRL/dev/ttyS1::INSTR
#   err opening instrument
#   ASRL/dev/ttyS2::INSTR
#   err opening instrument
#   ASRL/dev/ttyS3::INSTR
#   err opening instrument
#   ASRL/dev/rfcomm0::INSTR
#   SerialInstrument at ASRL/dev/rfcomm0::INSTR
#   probe
#   found PX100
#   2024-12-06 19:01:11.042 time_running=00:01:00 is_on=0.0 v=12.309 i=0.000 Ah=0.02 board_temp=23.0 i_setpoint=0.0 v_setpoint=0.0 timer_setpoint=00:00:00
#   2024-12-06 19:01:11.810 time_running=00:01:00 is_on=0.0 v=12.308 i=0.000 Ah=0.02 board_temp=23.0 i_setpoint=1.4 v_setpoint=0.0 timer_setpoint=00:00:00
#   ...
```

The GUI should show up, present the currently attached probe's voltage, and should allow controlling the DL24 device:

![Screenshot_20241206_190432](https://github.com/user-attachments/assets/83c1f580-d9b3-45cf-abf5-690f16329067)

**Comment by sbasmanov** [comment]
May be somebody knows, how to debug my issue? DL24MP fw 2.2, Mac OS 13.7.1, Python 3.13.1
Tried both misdoro's and Jay2k1. DL24 paired with MacBook M1. When app starts:
```
ASRL/dev/cu.DL24M_SPP::INSTR
SerialInstrument at ASRL/dev/cu.DL24M_SPP::INSTR
probe
Receive error
ko
No instruments found

```

If I try to cat port, I see this:
```
cat /dev/cu.DL24M_SPP
?Ui<Q?Ui<)?Ui<?Ui<??Ui<?Ui<??Ui<9?Ui<C?Ui<??Ui<#?Ui<??Ui<^C

and 

cat -v /dev/cu.DL24M_SPP
?U^A^B^@^@^@^@^@^@^@^@i^@^@^@^A^@^@^@^@^@^@^@^@^Y^@^@^@^@<^@^@^@^@/?U^A^B^@^@^@^@^@^@^@^@i^@^@^@^A^@^@^@^@^@^@^@^@^Y^@^@^@^@<^@^@^@^@??U^A^B^@^@^@^@^@^@^@^@i^@^@^@^A^@^@^@^@^@^@^@^@^Y^@^@^@^@<^@^@^@^@S?U^A^B^@^@^@^@^@^@^@^@i^@^@^@^A^@^@^@^@^@^@^@^@^Y^@^@^@^@<^@^@^@^@??U^A^B^@^@^@^@^@^@^@^@i^@^@^@^A^@^@^@^@^@^@^@^@^Y^@^@^@^@<^@^@^@^@^N?U^A^B^@^@^@^@^@^@^@^@i^@^@^@^A^@^@^@^@^@^@^@^@^Y^@^@^@^@<^@^@^@^@3?U^A^B^@^@^@^@^@^@^@^@i^@^@^@^A^@^@^@^@^@^@^@^@^Y^@^@^@^@<^@^@^@^@??U^A^B^@^@^@^@^@^@^@^@i^@^@^@^A^@^@^@^@^@^@^@^@^Y^@^@^@^@<^@^@^@^@^E?U^A^B^@^@^@^@^@^@^@^@i^@^@^@^A^@^@^@^@^@^@^@^@^Y^@^@^@^@<^@^@^@^@*?U^A^B^@^@^@^@^@^@^@^@i^@^@^@^A^@^@^@^@^@^@^@^@^Y^@^@^@^@<^@^@^@^@?^C
```


But it takes few seconds between starting cat and blue led on DL24. I increased timeout from 500 to 5000 - still not detecting device. 
It works from Win11 VM (parallels) with USB BT dongle (not internal Mac BT) with original Atorch software (very unstable, hangs all the time).
So, any ideas what to look for, to make it work?

Thanks.

**Comment by sbasmanov** [comment]
It seems that DL24M is using different protocol. Here is my dump from port:
```
od -t x1 /dev/cu.DL24M_SPP
0000000    ff  55  01  02  00  00  00  00  00  00  00  00  69  00  00  00
0000020    01  00  00  00  00  00  00  00  00  19  00  00  00  00  3c  00
0000040    00  00  00  36  ff  55  01  02  00  00  00  00  00  00  00  00
0000060    69  00  00  00  01  00  00  00  00  00  00  00  00  19  00  00
0000100    00  00  3c  00  00  00  00  4f  ff  55  01  02  00  00  00  00
0000120    00  00  00  00  69  00  00  00  01  00  00  00  00  00  00  00
0000140    00  19  00  00  00  00  3c  00  00  00  00  60  ff  55  01  02
0000160    00  00  00  00  00  00  00  00  69  00  00  00  01  00  00  00
0000200    00  00  00  00  00  19  00  00  00  00  3c  00  00  00  00  71
0000220    ff  55  01  02  00  00  00  00  00  00  00  00  69  00  00  00
0000240    01  00  00  00  00  00  00  00  00  19  00  00  00  00  3c  00
0000260    00  00  00  02  ff  55  01  02  00  00  00  00  00  00  00  00
0000300    69  00  00  00  01  00  00  00  00  00  00  00  00  19  00  00
0000320    00  00  3c  00  00  00  00  7d  ff  55  01  02  00  00  00  00
0000340    00  00  00  00  69  00  00  00  01  00  00  00  00  00  00  00
0000360    00  19  00  00  00  00  3c  00  00  00  00  f0  ff  55  01  02
0000400    00  00  00  00  00  00  00  00  69  00  00  00  01  00  00  00
0000420    00  00  00  00  00  19  00  00  00  00  3c  00  00  00  00  63
0000440    ff  55  01  02  00  00  00  00  00  00  00  00  69  00  00  00
0000460    01  00  00  00  00  00  00  00  00  19  00  00  00  00  3c  00
0000500    00  00  00  de  ff  55  01  02  00  00  00  00  00  00  00  00
0000520    69  00  00  00  01  00  00  00  00  00  00  00  00  19  00  00
0000540    00  00  3c  00  00  00  00  51  ff  55  01  02  00  00  00  00
0000560    00  00  00  00  69  00  00  00  01  00  00  00  00  00  00  00
0000600    00  19  00  00  00  00  3c  00  00  00  00  fb  ff  55  01  02
0000620    00  00  00  00  00  00  00  00  69  00  00  00  01  00  00  00
0000640    00  00  00  00  00  19  00  00  00  00  3c  00  00  00  00  2d
0000660    ff  55  01  02  00  00  00  00  00  00  00  00  69  00  00  00
0000700    01  00  00  00  00  00  00  00  00  19  00  00  00  00  3c  00

```

And here is implementation of this protocol:
https://github.com/syssi/esphome-atorch-dl24/blob/main/components/atorch_dl24/atorch_dl24.cpp
So, this software will not work with it :(

**Comment by kpbicka** [comment]
Same problem with purple board DL24MP  Ver 2.2, Mac OS 26 - not connect
