### ISSUE TITLE
Crashes when starting

### ISSUE THREAD

**Issue by menachers** [misdoro/Electronic_load_px100#3]
Hello,

I get a crash when starting the script.
I use python 3.8 on windows 10 and followed your instructions.
The load is conected at COM4 (USB-Serial CH340 at 3V3)

C:\Users\Stefan\Downloads\Electronic_load_px100-master>py -3 main.py
C:\Users\Stefan\AppData\Roaming\Python\Python38\site-packages\visa.py:13: FutureWarning: The visa module provided by PyVISA is being deprecated. You can replace `import visa` by `import pyvisa as visa` to achieve the same effect.

The reason for the deprecation is the possible conflict with the visa package provided by the https://github.com/visa-sdk/visa-python which can result in hard to debug situations.
  warnings.warn(
swcccv_reset
Detecting instruments...
ASRL1::INSTR
SerialInstrument at ASRL1::INSTR
probe
no answer
ko
ASRL4::INSTR
SerialInstrument at ASRL4::INSTR
probe
found PX100
readAll
Traceback (most recent call last):
  File "C:\Users\Stefan\Downloads\Electronic_load_px100-master\instr_thread.py", line 40, in run
    self.signals.data_row.emit(self.instr.readAll())
  File "C:\Users\Stefan\Downloads\Electronic_load_px100-master\instruments\px100.py", line 121, in readAll
    self.__clear_device()
  File "C:\Users\Stefan\Downloads\Electronic_load_px100-master\instruments\px100.py", line 220, in __clear_device
    self.device.clear()
  File "C:\Users\Stefan\AppData\Roaming\Python\Python38\site-packages\pyvisa\resources\resource.py", line 397, in clear
    self.visalib.clear(self.session)
  File "C:\Users\Stefan\AppData\Roaming\Python\Python38\site-packages\pyvisa_py\highlevel.py", line 191, in clear
    return self.handle_return_value(session, sess.clear())
  File "C:\Users\Stefan\AppData\Roaming\Python\Python38\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_NSUP_OPER (-1073807257): The given session or object reference does not support this operation.

C:\Users\Stefan\Downloads\Electronic_load_px100-master>

**Comment by misdoro** [comment]
Thanks for raising it @menachers. Looks like an incompatibility with the most recent pyvisa version. I'll try to have a look this weekend. In the meantime removing the `self.device.clear()` line might solve the issue.

**Comment by menachers** [comment]
Thank you for the feedback. I was not able to have a closer look onto the topic but downgrading PyVISA 1.10.1 solved it so far.
They removed deprecated functions and attributes when changing the version- maybe thats the reason.
https://pypi.org/project/PyVISA/1.11.0/
